- lib/controller.py
- lib/node.py
added -T with dmesg in controller.py for printing timestamp with kernel logs in collectinfo
Unfortunately timestamp can not be printed in Centos with dmesg, storing dmesg logs without timestamp for this OS.
code tested on ubuntu(12.04, 14.04), Debian 6, CentOS(5,6).
Please review the code and share your thoughts for this code change.
> AER-3455 added dmesg with timestamp in collectinfo

- lib/live_cluster/client/cluster.py
- lib/live_cluster/client/node.py
Asadm currently supports a proxy load-balancer in which an LB routes each request to a new node and proxies the node response.  When a DNS LB is used it is the responsibility of the DNS server to return a new IP every time the lookup is done.  The former was handled by making a single request to the node for all the needed connection information.  However, we were less careful when getting the IP and fqdn.  This caused the initial connection to happen on one node while the DNS lookup responded with a different node.  This eventually caused a later node to appear already in the cluster, triggering an eviction.
> TOOLS-2079 Support dns load-balancer

- Pipfile
- Pipfile.lock
- asadm.py
- lib/base_controller.py
- lib/live_cluster/client/__init__.py
- lib/live_cluster/client/constants.py
- lib/live_cluster/client/ctx.py
- lib/live_cluster/client/info.py
- lib/live_cluster/client/msgpack.py
- lib/live_cluster/client/node.py
- lib/live_cluster/client/types.py
- lib/live_cluster/live_cluster_command_controller.py
- lib/live_cluster/manage_controller.py
- lib/utils/constants.py
- lib/utils/util.py
- lib/view/sheet/decleration.py
- lib/view/templates.py
- test/unit/live_cluster/client/test_msgpack.py
- test/unit/live_cluster/client/test_node.py
- test/unit/live_cluster/test_manage_controller.py
[TOOLS-2066](https://aerospike.atlassian.net/browse/TOOLS-2066) (ASADM) Add sindex cardinality to `show sindex` and `info sindex` commands
[TOOLS-2063](https://aerospike.atlassian.net/browse/TOOLS-2063) (ASADM) Add the ability to create sindexs on CDTs by providing a context to the `manage sindex create` command.
[TOOLS-2061](https://aerospike.atlassian.net/browse/TOOLS-2061) (ASADM) Accept all characters for passwords except `;` and whitespace.
> Tools 2063 sindex cdt

- .github/workflows/mac-artifact.yml
- lib/live_cluster/collectinfo_controller.py
- lib/log_analyzer/log_handler/log_handler.py
[TOOLS-2097](https://aerospike.atlassian.net/browse/TOOLS-2097) (ASADM) LogAnalyzer fails when trying to hash logfile before it is converted to bytes.
Collectinfo cmd does not correctly restore prompt when finished.
> Bugfix 2.8.1

- lib/live_cluster/client/cluster.py
- lib/live_cluster/client/node.py
- lib/utils/lookup_dict.py
- test/unit/live_cluster/client/test_cluster.py
When the exact ip of a node is provided to the with modifier and there exists another node with an almost identical ip except for the last octet where the provided ip is a prefix of the other then an error will occur indicating that no matching nodes could be found.
Example:
User provides `with 1.1.1.1` and the list of available nodes is (1.1.1.11:3000, 1.1.1.1:3000) the correct response is  [1.1.1.1:3000] but with this bug an empty list would be returned.
> TOOLS-2220 Bug in the `with` modifier logic causes ip to not match

- lib/collectinfo_analyzer/info_controller.py
- lib/live_cluster/collectinfo_controller.py
- lib/view/view.py
The stats need to be flipped one more time for them to be correctly displayed.  Instead of adding another flip I removed a previous flip in live and collectinfo modes which had the same effect.
> fix: `info sindex` formatting

- Pipfile
- Pipfile.lock
It is causing issues with reading config schemas. Will fix in a later release.
> fix: Downgrade pyinstaller back to 4.10.

- asadm-asinfo-one-dir.spec
These spec files are really just python files.  I did two things. The most important is that I now bundle `/usr/lib64/libcrypt.so.1` with asadm. The location of that file is system dependent and is only needed for rhel9 so I only add it if we are linux.  We build our Linux bundles on centos7 and that is where the file is located. The second thing I did was remove the entire `lib` directory from the distribution.  When I first created the files I could not figure out how to only include the schemas and excluded the all the source files while still keeping the paths as asadm expects them.  Anyway, I figured it out hence the addition to the array `datas`.
> Tools 2380 rhel9

- asadm.py
There was a bug that caused an error to be displayed when a user used `quit` to exit. We are also reverting the change to how ctrl-c behaved to no anger users and to match expected interactive cmd line behavior
> Tools 2353 revert ctrl-c behavior

- Pipfile.lock
- lib/live_cluster/manage_controller.py
- test/unit/live_cluster/test_manage_controller.py
We were displaying the message for the namespace context when it should have been for the xdr/dc/namespace context
> fix: Tools 2512 incorrect enable compression

- lib/collectinfo_analyzer/collectinfo_handler/collectinfo_log.py
- test/e2e/live_cluster/test_all.py
Asadm 2.15.0 can't run commands that print a 'Node' column if the collectinfo file was not created with 2.15.0
> fix: TOOLS-2538 not able to parse collectinfo files

- asadm.py
- lib/live_cluster/live_cluster_root_controller.py
- lib/view/view.py
- test/e2e/lib.py
- test/e2e/live_cluster/test_all.py
The main change involves configuring a signal handler on the event loop to cancel tasks when a keyboard interrupt is received. In the original code it wasn't easy to guarantee the KeyboardInterrupt exception would propagate up as you would expect a normal exception to in a sync environment. Setting a CancelError exception makes the exception propagate as you'd expect rather than boil up to the event loop. We can play with this more in a code review if you'd like.
The last change is a small refactor of the watch controller and view logic. I moved stripped out some of the execution code from the view.watch method and put it in the controller to match the rest of the code design. Now the view code only displays, and the controller loops and executes the desired function. There is also a …
> Tools 2325 keyboard interrupt except

- lib/base_controller.py
- lib/collectinfo_analyzer/collectinfo_root_controller.py
- lib/collectinfo_analyzer/features_controller.py
- lib/collectinfo_analyzer/health_check_controller.py
- lib/collectinfo_analyzer/info_controller.py
- lib/collectinfo_analyzer/list_controller.py
- lib/collectinfo_analyzer/page_controller.py
- lib/collectinfo_analyzer/show_controller.py
- lib/collectinfo_analyzer/summary_controller.py
- lib/live_cluster/asinfo_controller.py
- lib/live_cluster/collectinfo_controller.py
- lib/live_cluster/features_controller.py
- lib/live_cluster/health_check_controller.py
- lib/live_cluster/info_controller.py
- lib/live_cluster/live_cluster_root_controller.py
- lib/live_cluster/manage_controller.py
- lib/live_cluster/pager_controller.py
- lib/live_cluster/show_controller.py
- lib/live_cluster/summary_controller.py
- lib/log_analyzer/log_analyzer_root_controller.py
- lib/utils/constants.py
- lib/view/terminal/terminal.py
- test/unit/live_cluster/test_manage_controller.py
- test/unit/test_base_controller.py
Examples of different output:
help
```
A tool for interacting with your Aerospike cluster.
Usage:   COMMAND
Commands:
Default         Print this help message
asinfo          Provides raw access to the info protocol
collectinfo     Collects cluster info, system stats, and aerospike conf file for local node
disable         Exits privileged mode
enable          Enters privileged mode
exit            Terminate session
features        Lists the features in use in a running Aerospike cluster
info            Provides summary tables for various aspects of Aerospike functionality
manage          Administrative tasks like managing users, roles, udf, and sindexes
pager           Turn terminal pager on or off
show            A collection of commands used to display information about the Aerospike …
```
> feat: TOOLS-2543 improve asadm help output

- lib/live_cluster/client/assocket.py
- lib/live_cluster/client/node.py
- lib/live_cluster/client/types.py
- lib/utils/logger.py
- test/unit/live_cluster/client/test_node.py
The problem was because of the import order in `logger.py`.  I found another potential future problem where certain ASInfoErrors and ASProtocolErrors should result in the Node being marked dead so I added a new ASProtocolError type and used multiple `except` statements.
> fix: Execute mode error does not have non-zero return code

- lib/live_cluster/client/config_handler.py
handles tls-authenticate-client config parameter
> fix: Handle cases where config param has "oneOf" key

- lib/live_cluster/generate_config_controller.py
- lib/live_cluster/live_cluster_root_controller.py
- lib/utils/conf_gen.py
- test/e2e/live_cluster/test_all.py
- test/e2e/live_cluster/test_confgen.py
- test/unit/utils/test_conf_gen.py
We now remove any empty contexts except for xdr.dc, xdr.dc.namespace, and security contexts.
The command `genconf` has also been renamed to `generate config`.
> TOOLS-2541 remove empty contexts and change name of genconf cmd

- lib/collectinfo_analyzer/info_controller.py
- lib/health/query.py
- lib/health/query/health.hql
- lib/live_cluster/info_controller.py
- lib/live_cluster/show_controller.py
- lib/utils/common.py
- lib/view/templates.py
- lib/view/view.py
- test/unit/utils/test_common.py
- test/unit/view/test_view.py
This PR includes:
- A redesign of the `info namespace usage` table to incorporate new `storage-engine.memory` design
- Updates to `summary` to incorporate new `storage-engine.memory` design
- An update to all healthchecks that use removed/renamed stats and configs
- Updates to the unique data usage calculation
> TOOLS-2669 TOOLS-2683 TOOLS-2705 TOOLS-2706 7.0 config/stats changes

- lib/live_cluster/client/config-schemas/4.0.0.json
- lib/live_cluster/client/config-schemas/4.1.0.json
- lib/live_cluster/client/config-schemas/4.2.0.json
- lib/live_cluster/client/config-schemas/4.3.0.json
- lib/live_cluster/client/config-schemas/4.3.1.json
- lib/live_cluster/client/config-schemas/4.4.0.json
- lib/live_cluster/client/config-schemas/4.5.0.json
- lib/live_cluster/client/config-schemas/4.5.1.json
- lib/live_cluster/client/config-schemas/4.5.2.json
- lib/live_cluster/client/config-schemas/4.5.3.json
- lib/live_cluster/client/config-schemas/4.6.0.json
- lib/live_cluster/client/config-schemas/4.7.0.json
- lib/live_cluster/client/config-schemas/4.8.0.json
- lib/live_cluster/client/config-schemas/4.9.0.json
- lib/live_cluster/client/config-schemas/5.0.0.json
- lib/live_cluster/client/config-schemas/5.1.0.json
- lib/live_cluster/client/config-schemas/5.2.0.json
- lib/live_cluster/client/config-schemas/5.3.0.json
- lib/live_cluster/client/config-schemas/5.4.0.json
- lib/live_cluster/client/config-schemas/5.5.0.json
- lib/live_cluster/client/config-schemas/5.6.0.json
- lib/live_cluster/client/config-schemas/5.7.0.json
- lib/live_cluster/client/config-schemas/6.0.0.json
- lib/live_cluster/client/config-schemas/6.1.0.json
- lib/live_cluster/client/config-schemas/6.2.0.json
- lib/live_cluster/client/config-schemas/6.3.0.json
- lib/live_cluster/client/config-schemas/6.4.0.json
- lib/live_cluster/client/config-schemas/7.0.0.json
fix: TOOLS-2797 `generate conf` does not properly save `data-in-memory` namespaces
Update 7.0 schema
> TOOLS-2771 TOOLS-2797 schema updates for all versions

- lib/live_cluster/generate_config_controller.py
- lib/live_cluster/ssh.py
Please look over the wording. I suspect since we only recently added this feature and have marked it has BETA we can remove it without issuing a breaking change release.
Ignore the ssh change. That is already in master
> Tools 2831 Deprecate `generate conf` cmd

- lib/live_cluster/client/node.py
Error Syntax has changed to ERROR:
~Checking what can be added as test for this.~
> fix: TOOLS-2964 Error Response from 7.2 for Show Latencies

- lib/live_cluster/client/assocket.py
- lib/live_cluster/client/node.py
Fixes set-stats if set is not present on a node.
> fix: TOOLS-2976 manage truncate fails when set DNE

- lib/utils/util.py
Build column should have F- for Federal edition
Fixes: TOOLS-2977 & TOOLS-2977
Simplifying the logic, Info Edition Calls to Server will not have true / false or CE / EE. Valid responses are 
- Aerospike Federal Edition build 6.4.0.15
- Aerospike Enterprise Edition
- Aeropsike Community Edition
> fix: TOOLS-2978 & TOOLS-2977 federal edition in build col

- .github/workflows/mac-artifact.yml
Remove macOS-12 from build as deprecated from gh
> build: Deprecate macos-12 Github-action

- lib/live_cluster/client/node.py
- test/unit/live_cluster/client/test_node.py
- remove {ns} from benchmarks-fabric.
- enabled only when verbose show latencies i.e show latencies -v
> fix:TOOLS-2984 removed {namespace} from benchmarks-fabric in latencies

- lib/live_cluster/client/constants.py
- lib/live_cluster/client/node.py
- test/unit/live_cluster/client/test_node.py
manage roster command was broken due to error standardization
The `unstable-cluster` string was changed `unstable cluster` which had to be handled.
> fix: TOOLS-2986 manage roster command fix

- .github/workflows/tests.yml
- lib/view/view.py
Server error response in certain cases are like :
objects=0:tombstones=0:data_used_bytes=0:truncate_lut=0:sindexes=0:index_populating=false:truncating=false:default-read-touch-ttl-pct=0:default-ttl=0:disable-eviction=true:enable-index=true:stop-writes-count=0:stop-writes-size=0;
where semicolon comes at the end. The delimiting logic has a higer precedence for semicolon and thus is not able to separate new lines by : double colon.
> fix: TOOLS-3003 strip/trim semi colon from resp for asinfo

- lib/live_cluster/client/constants.py
- lib/live_cluster/client/node.py
- lib/live_cluster/manage_controller.py
- test/unit/live_cluster/client/test_node.py
- test/unit/live_cluster/test_manage_controller.py
- removes special string handling
> fix: TOOLS-3012 standardise error handling string for manage roster

- Pipfile
- Pipfile.lock
Fixes -   https://www.cve.org/CVERecord?id=CVE-2024-12797
> dep: TOOLS-3011 update cryptography 44.0.1

- .github/workflows/mac-artifact.yml
actions/setup-python@v3 is deprecated and faling like 
```
Run actions/setup-python@v3
with:
python-version: 3.11
cache: pip
token: ***
env:
PYTHON_VERSION: 3.11
Successfully setup CPython (3.11.12)
/opt/hostedtoolcache/Python/3.11.12/x64/bin/pip cache dir
/home/runner/.cache/pip
Error: Cache service responded with 422
```
https://github.com/aerospike/aerospike-admin/actions/runs/14567722852/job/40859551963
> fix: update Python setup action to version 5

- lib/utils/log_util.py
- test/unit/collectinfo_analyzer/test_log_handler.py
On Mac, while extracting the collect_info.tgz, the file system generates forked files 
- more on it https://en.wikipedia.org/wiki/AppleSingle_and_AppleDouble_formats
An example
/collectinfo/77105/tmp/collect_info_20250408_064020/._20250408_064020_ascinfo.json
Contents
```
b'\x00\x05\x16\x07\x00\x02\x00\x00Mac OS X        \x00\x02\x00\x00\x00\t\x00\x00\x002\x00\x00\x00q\x00\x00\x00\x02\x00\x00\x00\xa3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00ATTR\x00\x00\x00\x00\x00\x00\x00\xa3\x00\x00\x00\x98\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x98\x00\x00\x00\x0b\x00\x00\x15com.apple.provenance\x00\x01\x02\x00Y\x86\xbc\xbe\xab\xe64\xc7
``` …
> fix: TOOLS-3035 add macOS resource fork file handling in log_util

- lib/live_cluster/client/info.py
- lib/live_cluster/client/types.py
- lib/view/templates.py
With this PR, it enables a new column for show users called Auth Mode.
The same will be available in CollectInfo Mode
Update. the column is moved to the end.
> feat: TOOLS-3054 add auth mode field to user info and templates

- lib/live_cluster/client/info.py
- test/unit/live_cluster/client/test_info.py
This PR updates the _receive_data function in lib/live_cluster/client/info.py to correctly handle cases where the server closes the connection before all expected data is received. Previously, if the server closed the connection early, the function could enter an infinite loop, causing client operations to hang indefinitely.
- Added a check for chunk == b"" (EOF) in the data reading loop.
- If EOF is encountered before all expected bytes are read, the function now raises a ConnectionResetError with a clear message.
- This ensures that:
- The client does not hang if the server disconnects unexpectedly.
- asyncio.wait_for timeouts are honored.
- Partial reads due to connection closure are treated as errors, not as empty or partial responses.
- All network protocol handlers that use …
> fix:TOOLS-3061 Improve data reception handling in _receive_data function

- test/e2e/live_cluster/test_show.py
Updated the expected headers in TestShowUsers to include 'Auth Mode' for improved test coverage and alignment with current output.
> fix: Add 'Auth Mode' to expected user table headers in tests

- .github/workflows/snyk-test.yml
Updated the Snyk CLI GitHub Action to use a specific commit hash and set the Snyk version to v1.1297.3 for improved reliability and reproducibility.
> chore: INFRA-103  Pin Snyk CLI action version in workflow

- lib/live_cluster/show_controller.py
A debug log statement was added to output the decoded user agent for each node, aiding in troubleshooting and monitoring user agent decoding.
> refactor: TOOLS-3060 add debug log for decoded user agent

- README.md
- test/e2e/lib.py
1. **Docker Image Version Pinning**
- Updated default Docker tag from `latest` to `"8.1"`
- I will later use the internal image, which points to build [requires docker auth setup] nightly
2. **Environment Variable Support**
- Added `E2E_TEST_USE_LOCALHOST` environment variable for macOS compatibility
- When set to `true`, tests use `127.0.0.1` instead of container IP addresses
- This resolves Docker networking issues on macOS where bridge network IPs are not accessible
The changes maintain backward compatibility while improving test reliability:
- Default behavior remains unchanged for Linux environments
- macOS users can now run tests successfully by setting `E2E_TEST_USE_LOCALHOST=true`
- Docker image version is now predictable and stable
For macOS users experiencing Docker networking …
> fix: Update E2E Tests: Pin Docker Image to 8.1 and Add Environment Variable Support for Mac

- lib/view/view.py
- test/unit/view/test_view.py
Clarifies the description for viewing individual user metrics by specifying the correct command syntax: 'show users statistics <username>'.
> fix: update user metrics help text in CLI view

- lib/utils/common.py
- test/unit/utils/test_common.py
The license data calculation in `_manually_compute_license_data_size()` had one critical issues:
**Incorrect global-level overhead calculation**: The function calculated record overhead at the namespace level, but this fails in mixed-version clusters where different hosts may run different Aerospike versions with different overhead requirements.
**Missing safety bounds**: License calculations could result in negative values when record overhead exceeded actual data size, particularly with small records, high compression ratios, or test environments.
Changed from namespace-level to per-host calculation logic:
**Before (Incorrect):**
```python
ns_unique_data = (total_data / repl_factor) - (total_objects * overhead)
```
**After (Correct):**
```python
for each host:
if host_version >= 8.0: …
```
> fix: TOOLS-3064 Fix license data calculation for mixed-version clusters and add safety clamping

- lib/utils/common.py
TCP state listen was in the manpage until 2017, but ss doesn't know such state
https://github.com/iproute2/iproute2/commit/ae4e21c93f81c8d612e4c72df44c2a1dc971a863
another related issue is that `ss` always prints a header even if no results are available, this results in the whole command returning a number that's by 1 higher than wanted every time. This is not an issue with the netstat commands because the grep filters the header out.
I didn't fix it in this PR because the `-H` flag was introduced in [iproute2 4.7](https://github.com/iproute2/iproute2/commit/7a4559f67c8c4dcd6d8d361018ac239090713b69) (Ubuntu 18.04, CentOS 7) and I don't know what distribution compatibility you are targeting.
> fix: collectinfo ss syntax

- lib/view/templates.py
- test/unit/view/test_view.py
This PR updates the `info namespace usage` view to support metrics introduced in Aerospike server versions 7.0 and later, while maintaining backward compatibility with older versions. The primary and secondary index usage calculations have been enhanced to handle different storage configurations (e.g., flash/pmem with mounts vs. in-memory) and prioritize newer metrics when available.
**Key Changes:**
*   **`lib/view/templates.py`**:
*   Modified `info_namespace_usage_sheet` to use `Projectors.Any` for calculating `Used%` for both "Primary Index" and "Secondary Index".
*   The logic now correctly prioritizes `index-type.mounts-budget` (for flash/pmem) and `indexes-memory-budget` (for in-memory indexes, added in 7.1) over older metrics.
*   It now uses `index_mounts_used_pct` and …
> fix: TOOLS-3063 fix Index Usage Calculation with Fallback Logic for Aerospike Version Compatibility

- lib/collectinfo_analyzer/info_controller.py
- lib/live_cluster/info_controller.py
- test/e2e/live_cluster/test_info.py
This PR improves the user experience for the `info` command in both live-cluster and collectinfo modes by explicitly rejecting unknown subcommands. Previously, entering an invalid subcommand (e.g., `info random`) would fall back to the default `info`, which could confuse users. Now, the CLI immediately returns a clear error message indicating the subcommand is invalid and suggests using help info for available options.
Additionally, an end-to-end test has been added to verify that unknown subcommands to info produce the correct error and do not show the default summary. This change ensures more predictable and user-friendly CLI behavior, aligning with standard practices in modern command-line tools.
> fix: TOOLS-3097 Improve CLI Error Handling: Reject Unknown Subcommands for info Command

- lib/live_cluster/manage_controller.py
- test/unit/live_cluster/test_manage_controller.py
Improves the validation logic to separately check for conflicts between 'ctx' and 'exp_base64', and 'ctx_base64' and 'exp_base64', providing more precise error messages for each case.
More on this https://aerospike.atlassian.net/browse/TOOLS-3065?focusedCommentId=165372
> fix: TOOLS-3065 Refine validation for mutually exclusive modifiers for sindex-create

- lib/live_cluster/client/client_util.py
- lib/live_cluster/client/node.py
- test/unit/live_cluster/client/test_cluster.py
- test/unit/live_cluster/client/test_node.py
This PR fixes a compatibility issue where asadm v4 was incompatible with Aerospike versions below 7.1 due to the "connection" info command not being available in older versions.
- The "connection" info command was introduced in Aerospike 8.1
- **Before 7.1**: Invalid commands are ignored (not included in response)
- **7.1-8.0**: Invalid commands return error strings
- The code was making a combined info call `["node", "features", "connection"]` and trying to access the 'connection' key
- On versions below 7.1, this caused either missing key errors or error string values, breaking node initialization
- **Separate connection probe**: First make a standalone "connection" info call to detect admin port status
- **Graceful fallback**: If the "connection" command is not available or returns an …
> fix: TOOLS-3106 Fixed asadm 7.1 Aerospike Version Compatibility for Admin Port Detection
